name = "bugbot-gateway"
main = "src/index.ts"
compatibility_date = "2024-01-01"

# Queues
[[queues.producers]]
queue = "bugbot-commands"
binding = "BUGBOT_QUEUE"

# KV namespaces
[[kv_namespaces]]
binding = "BUGBOT_KV"
id = "2a3a489ed1054ff1a33be4d27cdbf11c"
preview_id = "98d654c9428e472e84c7f285993b90ee"

# Secrets (set via: wrangler secret put <NAME>)
# DISCORD_PUBLIC_KEY
# DISCORD_BOT_TOKEN
